DROP TABLE IF EXISTS BACKGROUND;

CREATE TABLE BACKGROUND (
    BACKGROUND_NAME VARCHAR(30) NOT NULL CONSTRAINT PK_BACKGROUND_NAME PRIMARY KEY,  -- Use BACKGROUND_NAME as primary key
    TOOL_PROFICIENCIES VARCHAR(99),
    LANGUAGE VARCHAR(99),
    STARTING_EQUIPMENT VARCHAR(999) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    FEATURES TEXT,
    PERSONALITY_TRAITS TEXT,
    IDEALS TEXT,
    BONDS TEXT,
    FLAWS TEXT
);
