DROP TABLE IF EXISTS CAMPAIGN;

CREATE TABLE CAMPAIGN
(
    CAMPAIGN_ID INT CONSTRAINT PK_CAMPAIGN_ID PRIMARY KEY,
    TITLE VARCHAR(50) NOT NULL,
    START_DATE VARCHAR(10) NOT NULL,
    END_DATE VARCHAR(10) NOT NULL,
    DESCRIPTION VARCHAR(999) NOT NULL
);
