DROP TABLE IF EXISTS PLAYER;

CREATE TABLE PLAYER
(
    PLAYER_ID INT CONSTRAINT PK_PLAYER_USERNAME PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PLAYER_NAME VARCHAR(50) NOT NULL,
    ROLE VARCHAR(30) NOT NULL
);
