DROP TABLE IF EXISTS SKILL;

CREATE TABLE SKILL (
    SKILL_NAME VARCHAR(50) NOT NULL PRIMARY KEY,
    RELATED_ABILITY_SCORE VARCHAR(30) NOT NULL,
    PROFICIENCY_LEVEL VARCHAR(20) CHECK (PROFICIENCY_LEVEL IN ('Proficient', 'Expertise', NULL)),
    MODIFIER INT NOT NULL,
    TOTAL_BONUS INT NOT NULL,
    CHAR_ID VARCHAR(30) NOT NULL,  -- Foreign key from the CHARACTER table
    CONSTRAINT FK_SKILL_CHAR FOREIGN KEY (CHAR_ID) REFERENCES CHARACTER (CHAR_ID)
);
