DROP TABLE IF EXISTS SPECIES;

CREATE TABLE SPECIES
(
    SPECIES_NAME VARCHAR(30) NOT NULL CONSTRAINT PK_SPECIES_NAME PRIMARY KEY,
    SIZE VARCHAR(20) NOT NULL DEFAULT 'Medium',
    SPEED INT NOT NULL CONSTRAINT CK_SPECIES__BNS CHECK (SPEED >= 0) DEFAULT 30,
    DESCRIPTION VARCHAR(999) NOT NULL
);
