DROP TABLE IF EXISTS TRAIT;

CREATE TABLE TRAIT (
    TRAIT_ID int NOT NULL CONSTRAINT PK_Trait PRIMARY KEY, -- Unique identifier for each trait
    RACE VARCHAR(100) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT NOT NULL
);
